#!/usr/bin/env bash

# Check if number of arguments is less than 3
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

# Transfer file to the server
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP":~/

# Check if scp command was successful
if [ "$?" -eq 0 ]; then
    echo "File transferred successfully"
else
    echo "Error: File transfer failed"
fi
